# eks-app.yaml
apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
spec:
  selector:
    app.kubernetes.io/name: eks-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: 463470973103.dkr.ecr.ap-northeast-2.amazonaws.com:91ace4f29d92b2fd68484f94ccfb7f85359a08e8
        ports:
          - protocol: TCP
            containerPort: 8080
